# Generated by Django 4.0.5 on 2023-02-03 12:45

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Employee')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.IntegerField(default=0)),
                ('is_completed', models.IntegerField(default=0)),
                ('is_overdue', models.IntegerField(default=0)),
                ('headline', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 45, 33, 47311))),
                ('closed_at', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 45, 33, 47311))),
                ('deadline', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 45, 33, 47311))),
                ('task_time', models.TimeField(default=datetime.time(12, 45, 33, 47311))),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('current_date', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 45, 33, 48311))),
                ('completed_tasks', models.IntegerField(default=0)),
                ('active_tasks', models.IntegerField(default=0)),
                ('uncompleted_tasks', models.IntegerField(default=0)),
                ('working_hours', models.IntegerField(default=0)),
                ('working_minutes', models.IntegerField(default=0)),
                ('pause_hours', models.IntegerField(default=0)),
                ('pause_minutes', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_pause_date', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 45, 33, 48311))),
                ('finish_pause_date', models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 45, 33, 48311))),
                ('task_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.tasks')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
