# Generated by Django 4.0.5 on 2023-02-05 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(default='Normal', max_length=25),
        ),
        migrations.AlterField(
            model_name='pause',
            name='finish_pause_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 17, 20, 44, 993113)),
        ),
        migrations.AlterField(
            model_name='pause',
            name='start_pause_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 17, 20, 44, 993113)),
        ),
        migrations.AlterField(
            model_name='report',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 17, 20, 44, 992112)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 17, 20, 44, 992112)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 17, 20, 44, 992112)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 17, 20, 44, 992112)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_time',
            field=models.TimeField(default=datetime.time(17, 20, 44, 992112)),
        ),
    ]
