# Generated by Django 4.0.5 on 2023-02-07 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pause_pause_details_alter_pause_finish_pause_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='finish_pause_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 14, 8, 38, 498562)),
        ),
        migrations.AddField(
            model_name='tasks',
            name='location',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tasks',
            name='pause_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tasks',
            name='pause_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 7, 14, 8, 38, 498562)),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_pause_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 14, 8, 38, 498562)),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_effective_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 7, 14, 8, 38, 498562)),
        ),
        migrations.AlterField(
            model_name='report',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 14, 8, 38, 499562)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 14, 8, 38, 498562)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 14, 8, 38, 498562)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 14, 8, 38, 498562)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_time',
            field=models.TimeField(default=datetime.time(14, 8, 38, 498562)),
        ),
        migrations.DeleteModel(
            name='Pause',
        ),
    ]
