# Generated by Django 4.0.5 on 2023-02-08 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_report_active_tasks_remove_report_pause_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 588509)),
        ),
        migrations.AlterField(
            model_name='report',
            name='pause_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 588509)),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(default='Daily', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='work_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 588509)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 587508)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 587508)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='finish_pause_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 587508)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='pause_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 587508)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_pause_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 587508)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 587508)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_effective_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 8, 10, 8, 7, 587508)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_time',
            field=models.TimeField(default=datetime.time(10, 8, 7, 587508)),
        ),
    ]
