// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCugCZ4a_keMtaDAIEPXWp6TLCzR_a4nok',
    appId: '1:203284684089:android:6c08ab32e262f424e49ce8',
    messagingSenderId: '203284684089',
    projectId: 'employeesmanagementnotif',
    databaseURL: 'https://employeesmanagementnotif-default-rtdb.firebaseio.com',
    storageBucket: 'employeesmanagementnotif.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV_nsWSKivVdNSxX1zbXqJ79PYR0tXYC4',
    appId: '1:203284684089:ios:56d044100405c7c8e49ce8',
    messagingSenderId: '203284684089',
    projectId: 'employeesmanagementnotif',
    databaseURL: 'https://employeesmanagementnotif-default-rtdb.firebaseio.com',
    storageBucket: 'employeesmanagementnotif.appspot.com',
    iosClientId: '203284684089-f448i4nk7l0stesveh8639l66g3sj0pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeManagement',
  );
}
