# Generated by Django 4.0.5 on 2023-02-13 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pause',
            name='finish_pause_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 22, 20, 530163)),
        ),
        migrations.AlterField(
            model_name='pause',
            name='start_pause_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 22, 20, 530163)),
        ),
        migrations.AlterField(
            model_name='report',
            name='current_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 22, 20, 529163)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 22, 20, 528163)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 22, 20, 528163)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 22, 20, 528163)),
        ),
    ]
